---
title: "econ"
author: "Kirby Bartlett"
date: "February 3, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages

library(tidyverse)
library(rnaturalearth)
library(raster)

```

Read in Rasters
```{r}

# Read in the Empty Raster
empty_rast_econ <- raster("empty_raster.tif")

# Read in EEZ Raster
eez_econ <- raster("eez_all_1.tif")

# Read in Distance to Shore Raster
dist_shore_econ <- raster("dist_shore.tif")
```

Setting Number of Farms per Cell
```{r}

num_farms <- 1 # number of farms per 9.2x9.2 km cell, most conservative estimate of 16 cages per/farm (per cell)
```

Calculate Fuel Costs
```{r}

############# 2/2: We're going to change the harvestable fish weight to 5kg!

# Determine Fuel Costs and Usage
fuel_consumption <- 26.96 #L/hour
vessel_speed <- 15 #average speed in km/hr
diesel_price <- 0.92 #USD/L using 2020 exchange rate 1 usd = 4 reais
distance_to_port <- 25 #depend on cell
num_of_boats <- 2

trips_annual <- 416 # roundtrips per farm per year, for 2 boats (1 boat @ 5 trips/week, 1 @ 8 trips per week, and 52 weeks a year)
one_way_trips_annual <- 2*trips_annual # (we have to double the roundtrips because we need to take into account that distance traveled happens TWICE for every round trip)

# Create raster for all fuel costs:
annual_fuel_cost_econ <- (dist_shore_econ/vessel_speed)*fuel_consumption*diesel_price*one_way_trips_annual
plot(annual_fuel_cost_econ)


# Export Fuel Cost Raster by Distance to Shore
```

Calculate Wage Costs
```{r}

# Determine Total Wage Costs
cage_size <- 6400 #m^3
farm_size <- 16 #cages
farm_volume <- 102400 #m^3

full_time_workers <- 40
monthly_hours <- 160 #hours/month per fulltime employee
annual_hours <- (monthly_hours*12)
num_of_employees <-  ##/farm
hourly_wage <- 4.50 #USD/hour average
work_days_per_month <- 20
workers_offshore <- 35
workers_onshore <- 5

# Determine Annual Fixed Wage Cost per Farm
fixed_labor_cost <- full_time_workers*hourly_wage*annual_hours


# Determine # of Annual Transit Hours
annual_transit_hours <- (dist_shore_econ/vessel_speed)*one_way_trips_annual

# Determine Annual Wage Cost for Transit Hours Per Farm
transit_cost <- workers_offshore*annual_transit_hours*hourly_wage

# Create raster for all wage costs
total_annual_wage_costs <- transit_cost+fixed_labor_cost

plot(total_annual_wage_costs)

```

Calculate Annuity Function
```{r}

# Define the discount rate
risk_rho <- 1.17647
risk_discount <- (1-(1/risk_rho))

# Annuity Function
annuity <- function(c, r = risk_discount, t = 10) {
  a <- c/ ((1-(1+r)^-t)/r)
  return(a)
}
```

Calculate Capital Costs
```{r}

##### Discount rate comes into play for NPV equation, later.


# Farm Design
cage_cost <- 312000
weight_at_harvest <- 3 #user inputs (value is 3kg)
final_stocking_density <- 10 #user inputs (value is 10fish/m^3)
initial_stocking_density <- 3 #user inputs 3fish/m^3)
feed_conversion_ratio <- 3 #user inputs
survival_rate <- .85 #note that this is species-specific
fingerling_price <- 1.50 #USD ****
feed_price <- 2.10 #USD/kg ****
optimal_feed <- 2350080 #kg er farm/grow out cycle total amount of feed
time <- 12 #months, rotation period
farm_installation <- 139700
cage_installation <- (farm_installation/farm_size)
 
# One time costs
farm_lease <- 8668.74 #one-time lease
signaling_system <- 28021.40 #one-time system installation
project_development <- 53403.69 #project development
miscellaneous <- 123685.54 # one time
boats <- 420376.85 #for 3 boats, one time, 1 * 16m, 2* 7m

# Annual fixed costs
electric_power <- 3661.32
mooring_maintenance <- 53191.29
diving_maintenance <- 8427.13
office_rent <- 36626.43
environmental_monitoring <- 45781.04
annual_fixed_costs <- (electric_power + mooring_maintenance + diving_maintenance + office_rent + environmental_monitoring) #yearly costs
one_time_fixed_costs_depreciated <- (signaling_system + miscellaneous + boats) # find out how to apply annuity
one_time_fixed_costs_ndepreciated <- (farm_lease + project_development)
feed_annual <- (optimal_feed*feed_price)
 
# Fingerling costs
juv_cost_annual <- (initial_stocking_density*farm_volume*fingerling_price) #yearly cost
 

cage_cost_once <- ((farm_size*cage_cost)+farm_size*cage_installation) # one time #find out how to apply annuity
one_time_total <- (cage_cost_once + one_time_fixed_costs_depreciated + one_time_fixed_costs_ndepreciated)
   
# Total capital costs year 1
cap_cost_intial <- one_time_total + juv_cost_annual + annual_fixed_costs + feed_annual
cap_cost_intial
costs_fuel_wage <- overlay(annual_labor_cost_rast, #where is the annual_labor_cost_rast
                     annual_labor_cost_rast,
                     one_time_total,
                     fun = function(a, b){a+b})
plot(costs_fuel_wage)
total <- costs_fuel_wage+ one_time_total
plot(total)
freq(total)
freq(costs_fuel_wage)
```











```{r}
# Test with Suitability Raster

# Read in suitable.tif
suitable_tif <- raster("maricultura-app/data/suitability_map-2.tif")

# Mask the wage and fuel cost raster to suitable sites
# Get rid of 0 values

suitable_costs_overlay <- reclassify(suitable_tif, cbind(0, NA))

profitablity_suit <- mask(costs_fuel_wage, suitable_costs_overlay)

plot(profitablity_suit)

freq(profitablity_suit)
```

